name: 'DBT_DWH_ATM'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  SF_DBT_DWH_ATM:
    example:
      materialized: table

snapshots:
  DBT_DWH_ATM:
    +target_schema: 'DBT_DEV'
    +target_database: 'SF_DBT_DWH_ATM'
    +strategy: timestamp
    +updated_at: 'TS_LOADED_AT'
  
